export {default as clean} from './clean.task.js';
export {default as server} from './server.task.js';
export {default as watcher} from './watcher.task.js';
export {default as views} from './views.task.js';
export {default as styles} from './styles.task.js';
export {default as scripts} from './scripts.task.js';
export {default as fonts} from './fonts.task.js';
export {default as images} from './images.task.js';
export {default as config} from './config.js';
